apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
  labels:
    app: lanchonete-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lanchonete-deployment
  template:
    metadata:
      labels:
        app: lanchonete-deployment
    spec:
      containers:
        - name: lanchonete
          image: henriquedpaula/fiap-techchallenge:v1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_URL